platform :ios, '9.0'
use_frameworks!

target 'TALATracker' do
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 3.0'
    pod 'CVCalendar', '~> 1.2.6'
end

target 'TALATrackerTests' do

end

target 'TALATrackerUITests' do

end

