platform :ios, '9.0'
use_frameworks!

target 'TALATracker' do
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SwiftOverlays'
end

target 'TALATrackerTests' do

end

target 'TALATrackerUITests' do

end

