platform :ios, '8.0'
use_frameworks!

target 'TALATracker' do
    pod 'SnapKit'
    pod 'SwiftyJSON'
    pod 'Alamofire', '~> 3.0'
end

target 'TALATrackerTests' do

end

target 'TALATrackerUITests' do

end

